#!/usr/bin/env python3
"""Regenerate this plugin's documented-key allowlists from the Home Assistant
documentation repo, and report what changed.

Deterministic maintenance step for the update-from-docs skill. It regenerates
the closed allowlists of documented names (trigger/condition keys; template
functions/filters/tests) — the parts that can be rebuilt from a source of truth
and therefore cannot drift into fiction. It does NOT touch prose or YAML/Jinja
examples. Semantic changes (renamed option values, changed signatures) do not
show up in a name diff and must be reviewed by hand; see SKILL.md.

Usage:
    python3 sync_references.py --repo-root <checkout> --check  # preview
    python3 sync_references.py --repo-root <checkout> --only template-functions
    python3 sync_references.py --repo-root <checkout> --ref next --check    # preview an RC, write nothing

Auth: uses the public GitHub API. Set GITHUB_TOKEN to raise the rate limit.
"""
from __future__ import annotations

import argparse
import collections
import json
import os
import re
import sys
import tempfile
import urllib.error
import urllib.request
from pathlib import Path

REPO = "home-assistant/home-assistant.io"


# --- reference definitions -------------------------------------------------
# Each reference: which repo dirs feed it, where it's written, how to group the
# names, and the file header (anti-hallucination rule). `{ref}` `{today}` and
# per-source `{counts}` are filled at render time.

PURPOSE_HEADER = """---
name: purpose-specific-keys
description: Authoritative allowlist of documented Home Assistant purpose-specific trigger and condition keys. Consult before emitting any `domain.key` trigger/condition to avoid hallucinating non-existent keys.
---

# Purpose-Specific Trigger & Condition Keys — Authoritative Allowlist

**Source:** `home-assistant/home-assistant.io` repo, `source/_triggers/` and `source/_conditions/` (branch `{ref}`).
**Snapshot:** deterministic names from branch `{ref}`; regenerated by update-from-docs.

## Contents

- [Usage](#how-to-use-this-file-anti-hallucination-rule)
{contents}

## How to use this file (anti-hallucination rule)

Emit a `domain.key` trigger or condition **only if**:
1. the key appears in the lists below, **or**
2. you confirm it exists by fetching its own doc page — `https://rc.home-assistant.io/triggers/<key>/` or `.../conditions/<key>/`. HTTP 200 verifies that a page exists, not target-version support or a guessed signature. Read the page and match its feature/version/schema before emission. Snapshot absence alone does not prove invalidity.

Never invent a key from a pattern. If a plausible key (e.g. `person.arrived_home`, `sensor.co2_high`) is absent here and its doc page 404s, it does not exist — fall back to generic `state`/`numeric_state`/`template`.

This snapshot can gain or lose entries; review removals and verify target-version compatibility. Absence here is not proof a key is invalid in a *newer* version — but it IS reason to verify via the doc page before use. A missing conversion (left generic) is safe; a hallucinated key that silently never fires is not.

The keys below include the generic core ones too (`state`, `numeric_state`, `event`, `time`, `time_pattern`, `sun`, `zone`, `homeassistant`), which remain valid and are the correct fallback.

"""

TEMPLATE_HEADER = """---
name: template-functions
description: Authoritative allowlist of documented Home Assistant template functions, filters, and tests. Consult before using any template function/filter/test to avoid hallucinating non-existent ones.
---

# Template Functions, Filters & Tests — Authoritative Allowlist

**Source:** `home-assistant/home-assistant.io` repo, `source/_template_functions/` (branch `{ref}`).
**Snapshot:** deterministic names from branch `{ref}`; regenerated by update-from-docs.

## Contents

- [Usage](#how-to-use-this-file-anti-hallucination-rule)
{contents}

## How to use this file (anti-hallucination rule)

Use a template function/filter/test **only if**:
1. its name appears in the list below, **or**
2. you confirm it exists by fetching its own doc page — `https://rc.home-assistant.io/template-functions/<name>/`. HTTP 200 verifies that a page exists, not target-version support or a guessed signature. Read the page and match its feature/version/schema before emission. Snapshot absence alone does not prove invalidity.

Most standard Jinja2 built-ins also work; this list is HA's documented set (HA-specific helpers plus the Jinja built-ins HA exposes). If a name is absent here and its doc page 404s, do not invent it — rewrite using a documented function. Many entries are available as more than one of function / filter / test; check the entry's own page for its exact signature and its `limited:` flag (whether it works in limited templates).

This snapshot can gain or lose entries; review removals and verify target-version compatibility.

"""

REFERENCES = {
    "purpose-keys": {
        "sources": [("triggers", "Triggers"), ("conditions", "Conditions")],
        "src_dir": "_{}",  # source/_triggers, source/_conditions
        "out": Path("skills/ha-automations/reference/purpose-specific-keys.md"),
        "group": "domain",
        "header": PURPOSE_HEADER,
    },
    "template-functions": {
        "sources": [("template_functions", "Functions, filters & tests")],
        "src_dir": "_{}",  # source/_template_functions
        "out": Path("skills/ha-templates/reference/template-functions.md"),
        "group": "alpha",
        "header": TEMPLATE_HEADER,
    },
}


class RefreshError(ValueError):
    """Safe context-bearing maintenance failure (never include credentials)."""


def fetch_names(src_dir: str, ref: str, reference: str = "unknown") -> list[str]:
    context = f"reference={reference}; branch={ref}; source={src_dir}"
    from urllib.parse import quote
    url = f"https://api.github.com/repos/{REPO}/contents/source/{quote(src_dir)}?ref={quote(ref, safe='')}"
    req = urllib.request.Request(url, headers={"Accept": "application/vnd.github+json"})
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.load(resp)
    except urllib.error.HTTPError as exc:
        raise RefreshError(f"{context}; HTTP status={exc.code}") from None
    except (OSError, ValueError):
        raise RefreshError(f"{context}; network or JSON payload error") from None
    if not isinstance(data, list) or not all(isinstance(x, dict) and isinstance(x.get("name"), str) for x in data):
        raise RefreshError(f"{context}; invalid directory payload")
    names = [x["name"][:-9] for x in data if x["name"].endswith(".markdown")]
    if not names or any(not re.fullmatch(r"[a-z0-9_.]+", n) for n in names):
        raise RefreshError(f"{context}; empty or invalid markdown names")
    return sorted(set(names))


def validate_root(root: Path) -> Path:
    supplied = root.expanduser().absolute()
    root = supplied.resolve()
    parts = root.parts
    # Recognize client runtime layouts even when supplied through symlink aliases.
    if any(parts[i:i+2] == (".codex", "plugins") or parts[i:i+2] == (".claude", "plugins")
           for i in range(len(parts)-1)) or "plugins/cache" in root.as_posix() or "plugins/cache" in supplied.as_posix():
        raise RefreshError(f"repo-root={root}; installed plugin/cache is not a source checkout")
    for marker in (".claude-plugin/plugin.json", ".codex-plugin/plugin.json", ".git"):
        if not (root / marker).exists():
            raise RefreshError(f"repo-root={root}; missing checkout marker {marker}")
    return root


def output_path(root: Path, relative: Path) -> Path:
    root = root.resolve()
    out = (root / relative).resolve()
    if not out.is_relative_to(root / "skills"):
        raise RefreshError(f"repo-root={root}; output escapes skills: {relative}")
    return out


def parse_existing(text: str) -> set[str]:
    return set(re.findall(r"^- `([a-z0-9_.]+)`", text, flags=re.MULTILINE))


def group_domain(names: list[str]):
    g: "collections.OrderedDict[str, list[str]]" = collections.OrderedDict()
    for n in names:
        dom = n.split(".", 1)[0] if "." in n else "(core/generic)"
        g.setdefault(dom, []).append(n)
    return g


def group_alpha(names: list[str]):
    g: "collections.OrderedDict[str, list[str]]" = collections.OrderedDict()
    for n in names:
        g.setdefault(n[0].upper(), []).append(n)
    return g


def render_section(title: str, names: list[str], how: str) -> str:
    grouper = group_domain if how == "domain" else group_alpha
    lines = [f"## {title} ({len(names)} entries)\n"]
    for key, keys in grouper(names).items():
        lines.append(f"### `{key}`" if how == "domain" else f"### {key}")
        lines.append("".join(f"\n- `{k}`" for k in keys))
        lines.append("")
    return "\n".join(lines)


def build(name: str, spec: dict, ref: str, root: Path):
    sections, all_names, contents = [], [], []
    for src, title in spec["sources"]:
        names = fetch_names(spec["src_dir"].format(src), ref, name)
        all_names += names
        sections.append(render_section(title, names, spec["group"]))
        anchor = re.sub(r"[^a-z0-9 -]", "", f"{title} ({len(names)} entries)".lower()).replace(" ", "-")
        contents.append(f"- [{title}](#{anchor})")
    out = output_path(root, spec["out"])
    try:
        old = out.read_bytes() if out.exists() else None
        previous = parse_existing(old.decode()) if old else set()
    except (OSError, UnicodeError):
        raise RefreshError(f"reference={name}; branch={ref}; output={spec['out']}; unreadable or non-UTF8 target") from None
    removed = sorted(previous - set(all_names))
    text = spec["header"].format(ref=ref, contents="\n".join(contents)) + "\n".join(sections)
    new = text.encode()
    return out, old, new, removed


def replace_batch(prepared):
    """Stage all files; restore byte-identical originals if replacement fails."""
    staged, replaced = [], []
    try:
        for out, old, new, removed in prepared:
            if old == new:
                continue
            out.parent.mkdir(parents=True, exist_ok=True)
            with tempfile.NamedTemporaryFile(dir=out.parent, delete=False) as handle:
                handle.write(new)
                staged.append((Path(handle.name), out, old))
        for temp, out, old in staged:
            os.replace(temp, out)
            replaced.append((out, old))
    except OSError:
        rollback_failures = []
        for out, old in reversed(replaced):
            try:
                if old is None:
                    out.unlink()
                else:
                    out.write_bytes(old)
            except OSError:
                rollback_failures.append(str(out))
        detail = " rollback failed: " + ", ".join(rollback_failures) if rollback_failures else " originals restored"
        raise RefreshError("staged replacement failed;" + detail) from None
    finally:
        for temp, _, _ in staged:
            temp.unlink(missing_ok=True)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo-root", required=True, type=Path, help="explicit source Git checkout")
    ap.add_argument("--ref", default="current")
    ap.add_argument("--check", action="store_true", help="preview only")
    ap.add_argument("--fail-on-drift", action="store_true", help="with --check: exit 1 on content drift")
    ap.add_argument("--approve-removals", action="store_true", help="apply removals already approved from preview")
    ap.add_argument("--only", choices=list(REFERENCES))
    args = ap.parse_args(argv)
    if args.fail_on_drift and not args.check:
        ap.error("--fail-on-drift requires --check")
    try:
        root = validate_root(args.repo_root)
        prepared = [build(name, spec, args.ref, root) for name, spec in REFERENCES.items()
                    if not args.only or name == args.only]
        changed = any(old != new for _, old, new, _ in prepared)
        for out, old, new, removed in prepared:
            print(f"{out.relative_to(root)}: {'drift' if old != new else 'unchanged'}")
            added = sorted(parse_existing(new.decode()) - parse_existing(old.decode() if old else ""))
            if added:
                print("  ADDED: " + ", ".join(added))
            if removed:
                print("  REMOVED/RENAMED: " + ", ".join(removed))
        if not args.check:
            if any(removed for _, _, _, removed in prepared) and not args.approve_removals:
                raise RefreshError("removals require reviewed approval; rerun with --approve-removals after approval")
            replace_batch(prepared)
        print("Preview only; no writes." if args.check else "Mechanical refresh complete; semantic edits require human approval.")
        return int(args.check and args.fail_on_drift and changed)
    except RefreshError as exc:
        print(str(exc), file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
