#!/usr/bin/env python3
"""Regenerate this plugin's documented-key allowlists from the Home Assistant
documentation repo, and report what changed.

Deterministic maintenance step for the update-from-docs skill. It regenerates
the closed allowlists of documented names (trigger/condition keys; template
functions/filters/tests) — the parts that can be rebuilt from a source of truth
and therefore cannot drift into fiction. It does NOT touch prose or YAML/Jinja
examples. Semantic changes (renamed option values, changed signatures) do not
show up in a name diff and must be reviewed by hand; see SKILL.md.

Usage:
    python3 sync_references.py                       # regenerate all, print diffs
    python3 sync_references.py --only template-functions
    python3 sync_references.py --ref next --check    # preview an RC, write nothing

Auth: uses the public GitHub API. Set GITHUB_TOKEN to raise the rate limit.
"""
from __future__ import annotations

import argparse
import collections
import datetime
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

REPO = "home-assistant/home-assistant.io"
SKILLS = Path(__file__).resolve().parents[1]  # .../skills

# --- reference definitions -------------------------------------------------
# Each reference: which repo dirs feed it, where it's written, how to group the
# names, and the file header (anti-hallucination rule). `{ref}` `{today}` and
# per-source `{counts}` are filled at render time.

PURPOSE_HEADER = """---
name: purpose-specific-keys
description: Authoritative allowlist of documented Home Assistant purpose-specific trigger and condition keys. Consult before emitting any `domain.key` trigger/condition to avoid hallucinating non-existent keys.
---

# Purpose-Specific Trigger & Condition Keys — Authoritative Allowlist

**Source:** `home-assistant/home-assistant.io` repo, `source/_triggers/` and `source/_conditions/` (branch `{ref}`).
**Captured:** {today} (regenerated by the update-from-docs skill).

## How to use this file (anti-hallucination rule)

Emit a `domain.key` trigger or condition **only if**:
1. the key appears in the lists below, **or**
2. you confirm it exists by fetching its own doc page — `https://rc.home-assistant.io/triggers/<key>/` or `.../conditions/<key>/`. **HTTP 200 = real; 404 = does not exist, do NOT use it.**

Never invent a key from a pattern. If a plausible key (e.g. `person.arrived_home`, `sensor.co2_high`) is absent here and its doc page 404s, it does not exist — fall back to generic `state`/`numeric_state`/`template`.

This list **grows every release**. Absence here is not proof a key is invalid in a *newer* version — but it IS reason to verify via the doc page before use. A missing conversion (left generic) is safe; a hallucinated key that silently never fires is not.

The keys below include the generic core ones too (`state`, `numeric_state`, `event`, `time`, `time_pattern`, `sun`, `zone`, `homeassistant`), which remain valid and are the correct fallback.

"""

TEMPLATE_HEADER = """---
name: template-functions
description: Authoritative allowlist of documented Home Assistant template functions, filters, and tests. Consult before using any template function/filter/test to avoid hallucinating non-existent ones.
---

# Template Functions, Filters & Tests — Authoritative Allowlist

**Source:** `home-assistant/home-assistant.io` repo, `source/_template_functions/` (branch `{ref}`).
**Captured:** {today} (regenerated by the update-from-docs skill).

## How to use this file (anti-hallucination rule)

Use a template function/filter/test **only if**:
1. its name appears in the list below, **or**
2. you confirm it exists by fetching its own doc page — `https://rc.home-assistant.io/template-functions/<name>/`. **HTTP 200 = real; 404 = does not exist, do NOT use it.**

Most standard Jinja2 built-ins also work; this list is HA's documented set (HA-specific helpers plus the Jinja built-ins HA exposes). If a name is absent here and its doc page 404s, do not invent it — rewrite using a documented function. Many entries are available as more than one of function / filter / test; check the entry's own page for its exact signature and its `limited:` flag (whether it works in limited templates).

This list **grows every release**.

"""

REFERENCES = {
    "purpose-keys": {
        "sources": [("triggers", "Triggers"), ("conditions", "Conditions")],
        "src_dir": "_{}",  # source/_triggers, source/_conditions
        "out": SKILLS / "ha-automations" / "reference" / "purpose-specific-keys.md",
        "group": "domain",
        "header": PURPOSE_HEADER,
    },
    "template-functions": {
        "sources": [("template_functions", "Functions, filters & tests")],
        "src_dir": "_{}",  # source/_template_functions
        "out": SKILLS / "ha-templates" / "reference" / "template-functions.md",
        "group": "alpha",
        "header": TEMPLATE_HEADER,
    },
}


def fetch_names(src_dir: str, ref: str) -> list[str]:
    url = f"https://api.github.com/repos/{REPO}/contents/source/{src_dir}?ref={ref}"
    req = urllib.request.Request(url, headers={"Accept": "application/vnd.github+json"})
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.load(resp)
    except urllib.error.HTTPError as e:  # pragma: no cover
        if e.code == 403:
            sys.exit("GitHub API rate-limited. Set GITHUB_TOKEN and retry.")
        raise
    return sorted(x["name"][:-9] for x in data if x["name"].endswith(".markdown"))


def parse_existing(text: str) -> set[str]:
    return set(re.findall(r"^- `([a-z0-9_.]+)`", text, flags=re.MULTILINE))


def group_domain(names: list[str]):
    g: "collections.OrderedDict[str, list[str]]" = collections.OrderedDict()
    for n in names:
        dom = n.split(".", 1)[0] if "." in n else "(core/generic)"
        g.setdefault(dom, []).append(n)
    return g


def group_alpha(names: list[str]):
    g: "collections.OrderedDict[str, list[str]]" = collections.OrderedDict()
    for n in names:
        g.setdefault(n[0].upper(), []).append(n)
    return g


def render_section(title: str, names: list[str], how: str) -> str:
    grouper = group_domain if how == "domain" else group_alpha
    lines = [f"## {title} ({len(names)} entries)\n"]
    for key, keys in grouper(names).items():
        lines.append(f"### `{key}`" if how == "domain" else f"### {key}")
        lines.append("".join(f"\n- `{k}`" for k in keys))
        lines.append("")
    return "\n".join(lines)


def build(name: str, spec: dict, ref: str, check: bool) -> bool:
    today = datetime.date.today().isoformat()
    all_names: list[str] = []
    sections: list[str] = []
    for src, title in spec["sources"]:
        names = fetch_names(spec["src_dir"].format(src), ref)
        all_names += names
        sections.append(render_section(title, names, spec["group"]))

    new_keys = set(all_names)
    out: Path = spec["out"]
    old_keys = parse_existing(out.read_text()) if out.exists() else set()
    added = sorted(new_keys - old_keys)
    removed = sorted(old_keys - new_keys)

    print(f"\n=== {name} ({out.relative_to(SKILLS.parent)}) ===")
    print(f"  entries: {len(new_keys)} (was {len(old_keys)})")
    for tag, items in (("ADDED", added), ("REMOVED/RENAMED", removed)):
        if items:
            print(f"  {tag} ({len(items)}): " + ", ".join(items))
    if not added and not removed:
        print("  no changes since last sync")

    if not check:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(spec["header"].format(ref=ref, today=today) + "\n".join(sections))
    return bool(added or removed)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ref", default="current", help="docs repo branch (default: current)")
    ap.add_argument("--check", action="store_true", help="report only; write nothing")
    ap.add_argument("--only", choices=list(REFERENCES), help="regenerate one reference")
    args = ap.parse_args()

    print(f"Branch: {args.ref}")
    changed = False
    for name, spec in REFERENCES.items():
        if args.only and name != args.only:
            continue
        changed |= build(name, spec, args.ref, args.check)

    if args.check:
        print("\n--check: no files modified.")
    elif changed:
        print(
            "\n⚠️  Names changed. Now do the JUDGMENT review (SKILL.md Step B): a "
            "name diff does NOT reveal renamed values, changed signatures, or "
            "syntax shifts. Check release notes and a sample of changed pages."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
